import React, {useState} from 'react'
import { CommanBanner, Pagination } from '@/components/components'
import banner from './Image/BlogSection.jpg'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'

export const paginate = (items, pageNumber, pageSize) => {
  const startIndex = (pageNumber - 1) * pageSize;
  return items.slice(startIndex, startIndex + pageSize);
 };



const Blog = ({ data }) => {
  
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;
  const paginatedPosts = paginate(data, currentPage, pageSize);
  console.log(paginatedPosts)
  const onPageChange = (page) => {
    setCurrentPage(page);
  };
  return (
   <>
    <CommanBanner  image ={banner} title ='Blog'/>
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <p>
      <strong>NextJS x Pagination</strong>
    </p>
    {paginatedPosts.map((item) => {
      return <p key={item.id}>{item.title}</p>;
    })}
   <Pagination
      items={data.length} // 100
      currentPage={currentPage} // 1
      pageSize={pageSize} // 10
      onPageChange={onPageChange}
       />
  </div>
   </>
  )
}
export default Blog

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();
 
  return {
    props: { data },
  };
 };